// export const FETCH_CLIENT_TOKEN = 'FETCH_CLIENT_TOKEN';
// export const SET_CLIENT_TOKEN = 'SET_CLIENT_TOKEN';
// export const SET_NONCE = 'SET_NONCE';
// export const SET_LIABILITY_SHIFTED = 'SET_LIABILITY_SHIFTED';
